import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import {
  assertSinglePageAtlas,
  buildSheetAssets,
  sheetImageFiles,
} from "./helpers";
import { toPascal, toSnake } from "../strings";

const toFloat = (n: number) => (Number.isInteger(n) ? `${n}.0` : `${n}`);

export const createBevySpritesheetRs = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const lines: string[] = [];
  const push = (...args: string[]) => lines.push(...args);

  const firstPascal = toPascal(json.animations[0]?.name ?? "Idle");

  push(
    `// Generated by Sprite Sheet Helper`,
    `// ${json.meta.exportedAt}`,
    `//`,
    `// Drop-in Bevy plugin — https://bevyengine.org`,
    `// Place "${imagePath}" in your assets/ folder, then in main:`,
    `//`,
    `//   App::new()`,
    `//       .add_plugins((DefaultPlugins, SpritesheetPlugin))`,
    `//       .run();`,
    `//`,
    `// Spawn an entity:`,
    `//   commands.spawn(AnimatedSpriteBundle::new(Animation::${firstPascal}, &asset_server));`,
    `//`,
    `// Switch animation at runtime:`,
    `//   *config = Animation::${firstPascal}.config();`,
    `//   config.reset(&mut sprite);`,
    ``,
    `use bevy::prelude::*;`,
    ``,
  );

  push(
    `// ─── Plugin ──────────────────────────────────────────────────────────────────`,
    ``,
    `pub struct SpritesheetPlugin;`,
    ``,
    `impl Plugin for SpritesheetPlugin {`,
    `    fn build(&self, app: &mut App) {`,
    `        app.add_systems(Update, animate_sprites);`,
    `    }`,
    `}`,
    ``,
  );

  push(
    `// ─── Component ───────────────────────────────────────────────────────────────`,
    ``,
    `#[derive(Component)]`,
    `pub struct AnimationConfig {`,
    `    frames:            &'static [Rect],`,
    `    pub frame_count:   usize,`,
    `    pub fps:           f32,`,
    `    pub current_frame: usize,`,
    `    timer:             Timer,`,
    `}`,
    ``,
    `impl AnimationConfig {`,
    `    pub fn new(frames: &'static [Rect], fps: f32) -> Self {`,
    `        Self {`,
    `            frame_count: frames.len(),`,
    `            frames,`,
    `            fps,`,
    `            current_frame: 0,`,
    `            timer: Timer::from_seconds(1.0 / fps, TimerMode::Repeating),`,
    `        }`,
    `    }`,
    ``,
    `    /// Advance to frame \`index\` (wraps around) and update the sprite rect.`,
    `    pub fn set_frame(&mut self, index: usize, sprite: &mut Sprite) {`,
    `        self.current_frame = index % self.frame_count;`,
    `        sprite.rect = Some(self.frames[self.current_frame]);`,
    `    }`,
    ``,
    `    /// Jump back to frame 0 and restart the timer.`,
    `    pub fn reset(&mut self, sprite: &mut Sprite) {`,
    `        self.timer.reset();`,
    `        self.set_frame(0, sprite);`,
    `    }`,
    `}`,
    ``,
  );

  push(
    `// ─── System ──────────────────────────────────────────────────────────────────`,
    ``,
    `pub fn animate_sprites(time: Res<Time>, mut query: Query<(&mut AnimationConfig, &mut Sprite)>) {`,
    `    for (mut config, mut sprite) in &mut query {`,
    `        config.timer.tick(time.delta());`,
    `        if config.timer.just_finished() {`,
    `            config.current_frame = (config.current_frame + 1) % config.frame_count;`,
    `            sprite.rect = Some(config.frames[config.current_frame]);`,
    `        }`,
    `    }`,
    `}`,
    ``,
  );

  push(
    `// ─── Frame data ──────────────────────────────────────────────────────────────`,
    ``,
    `pub const SPRITESHEET_PATH: &str = "${imagePath}";`,
    ``,
  );

  for (const anim of json.animations) {
    const constName = `${toSnake(anim.name).toUpperCase()}_FRAMES`;
    push(`#[rustfmt::skip]`);
    push(`static ${constName}: &[Rect] = &[`);
    for (const q of anim.quads) {
      push(
        `    Rect { min: Vec2::new(${toFloat(q.x)}, ${toFloat(q.y)}),` +
          ` max: Vec2::new(${toFloat(q.x + q.w)}, ${toFloat(q.y + q.h)}) },`,
      );
    }
    push(`];`);
    push(``);
  }

  push(
    `// ─── Animation enum ──────────────────────────────────────────────────────────`,
    ``,
    `/// All animations exported from this spritesheet.`,
    `/// Pass a variant to \`AnimatedSpriteBundle::new\` or swap it at runtime via \`config.reset\`.`,
    `#[derive(Debug, Clone, Copy, PartialEq, Eq)]`,
    `pub enum Animation {`,
  );
  for (const anim of json.animations) {
    push(`    ${toPascal(anim.name)},`);
  }
  push(`}`, ``);

  push(`impl Animation {`);

  // frames()
  push(
    `    /// Static frame rects for this animation.`,
    `    pub fn frames(self) -> &'static [Rect] {`,
    `        match self {`,
  );
  for (const anim of json.animations) {
    push(
      `            Animation::${toPascal(anim.name)} => ${toSnake(anim.name).toUpperCase()}_FRAMES,`,
    );
  }
  push(`        }`, `    }`, ``);

  // fps()
  push(
    `    /// Frames-per-second for this animation.`,
    `    pub fn fps(self) -> f32 {`,
    `        match self {`,
  );
  for (const anim of json.animations) {
    push(
      `            Animation::${toPascal(anim.name)} => ${toFloat(anim.fps)},`,
    );
  }
  push(`        }`, `    }`, ``);

  // config()
  push(
    `    /// Build an \`AnimationConfig\` ready to insert or swap onto an entity.`,
    `    pub fn config(self) -> AnimationConfig {`,
    `        AnimationConfig::new(self.frames(), self.fps())`,
    `    }`,
  );

  push(`}`, ``);

  // ── AnimatedSpriteBundle ─────────────────────────────────────────────────────
  push(
    `// ─── Bundle ──────────────────────────────────────────────────────────────────`,
    ``,
    `/// The single bundle for any animated sprite from this spritesheet.`,
    `///`,
    `/// \`\`\``,
    `/// commands.spawn(AnimatedSpriteBundle::new(Animation::${firstPascal}, &asset_server));`,
    `/// \`\`\``,
    `#[derive(Bundle)]`,
    `pub struct AnimatedSpriteBundle {`,
    `    pub sprite:               Sprite,`,
    `    pub transform:            Transform,`,
    `    pub global_transform:     GlobalTransform,`,
    `    pub visibility:           Visibility,`,
    `    pub inherited_visibility: InheritedVisibility,`,
    `    pub view_visibility:      ViewVisibility,`,
    `    pub animation:            AnimationConfig,`,
    `}`,
    ``,
    `impl AnimatedSpriteBundle {`,
    `    pub fn new(animation: Animation, asset_server: &AssetServer) -> Self {`,
    `        let config = animation.config();`,
    `        let first  = animation.frames()[0];`,
    `        Self {`,
    `            sprite: Sprite {`,
    `                image: asset_server.load(SPRITESHEET_PATH),`,
    `                rect:  Some(first),`,
    `                ..default()`,
    `            },`,
    `            transform:            Transform::default(),`,
    `            global_transform:     GlobalTransform::default(),`,
    `            visibility:           Visibility::default(),`,
    `            inherited_visibility: InheritedVisibility::default(),`,
    `            view_visibility:      ViewVisibility::default(),`,
    `            animation:            config,`,
    `        }`,
    `    }`,
    ``,
    `    /// Convenience builder: set world position before spawning.`,
    `    pub fn at(mut self, x: f32, y: f32, z: f32) -> Self {`,
    `        self.transform = Transform::from_xyz(x, y, z);`,
    `        self`,
    `    }`,
    `}`,
  );

  return lines.join("\n");
};

/**
 * A `main.rs` that declares every sheet's module and spawns from the first.
 *
 * Each sheet is a module, so the identical type names inside them do not
 * collide — the module path is the namespace, and every sheet's plugin is its
 * own type, so they can all be added to the same app.
 */
export const createBevyMainRs = (
  json: SpritesheetJSON,
  moduleNames: string[] = ["spritesheet"],
): string => {
  const firstPascal = toPascal(json.animations[0]?.name ?? "Idle");
  const [first, ...rest] = moduleNames;

  return [
    `use bevy::prelude::*;`,
    ``,
    ...moduleNames.map((name) => `mod ${name};`),
    `use ${first}::{Animation, AnimatedSpriteBundle, SpritesheetPlugin};`,
    ``,
    `fn main() {`,
    `    App::new()`,
    `        .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))`,
    `        .add_plugins(SpritesheetPlugin)`,
    ...rest.map((name) => `        .add_plugins(${name}::SpritesheetPlugin)`),
    `        .add_systems(Startup, setup)`,
    `        .run();`,
    `}`,
    ``,
    `fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {`,
    `    commands.spawn(Camera2d);`,
    `    commands.spawn(`,
    `        AnimatedSpriteBundle::new(Animation::${firstPascal}, &asset_server).at(0.0, 0.0, 0.0),`,
    `    );`,
    `}`,
  ].join("\n");
};

export const createBevyCargoToml = (): string =>
  [`# Add to your Cargo.toml [dependencies]`, `bevy = "0.15"`].join("\n");

export const bevyExporter: Exporter<"bevy"> = {
  id: "bevy",
  label: "Bevy",

  async run({
    exportedImages,
    includeNormalMap,
    atlasOptions,
    spritePostprocess,
  }) {
    const sheets = await buildSheetAssets(exportedImages, {
      includeNormalMap,
      atlasOptions,
      directory: "assets/",
      exporterId: "bevy",
      spritePostprocess,
    });
    for (const sheet of sheets) {
      assertSinglePageAtlas(sheet.assets, "Bevy");
    }
    // Rust modules are snake_case, and a sheet name is not.
    const moduleNames = sheets.map((sheet) => toSnake(sheet.base));

    return {
      filename: "bevy.zip",
      files: [
        ...sheets.flatMap((sheet, index) => [
          ...sheetImageFiles(sheet),
          sheet.assets.manifestFile,
          {
            name: `src/${moduleNames[index]}.rs`,
            content: createBevySpritesheetRs(
              sheet.assets.json,
              sheet.imagePath,
            ),
          },
        ]),
        {
          name: "src/main.rs",
          content: createBevyMainRs(sheets[0].assets.json, moduleNames),
        },
        { name: "Cargo.toml.snippet", content: createBevyCargoToml() },
      ],
    };
  },
};
