import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import {
  assertSinglePageAtlas,
  buildSheetAssets,
  sheetImageFiles,
} from "./helpers";
import { toSheetIdentifier } from "./sheets";

/**
 * `class_name` is global in Godot, so one class per sheet: a grouped export
 * that reused `SpriteSheetHelper` would fail to parse the moment both scripts
 * were in the project. A single sheet keeps the original name.
 */
export const createGodotGD = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
  className = "SpriteSheetHelper",
): string => {
  const T = "\t"; // GDScript indents with tabs
  const lines: string[] = [];

  lines.push(`# Generated by Sprite Sheet Helper`);
  lines.push(`# ${json.meta.exportedAt}`);
  lines.push(`#`);
  lines.push(`# Place "${imagePath}" in your project (e.g. res://assets/) and`);
  lines.push(`# update SHEET_PATH below.`);
  lines.push(`#`);
  lines.push(`# Usage:`);
  lines.push(`#   var animated_sprite := AnimatedSprite2D.new()`);
  lines.push(
    `#   animated_sprite.sprite_frames = ${className}.create_sprite_frames()`,
  );
  lines.push(
    `#   animated_sprite.play("${json.animations[0]?.name ?? "walk"}")`,
  );
  lines.push(`#   add_child(animated_sprite)`);
  lines.push(``);
  lines.push(`class_name ${className}`);
  lines.push(`extends RefCounted`);
  lines.push(``);
  lines.push(`const SHEET_PATH = "res://${imagePath}"`);
  lines.push(``);
  lines.push(`static func create_sprite_frames() -> SpriteFrames:`);
  lines.push(`${T}var texture: Texture2D = load(SHEET_PATH)`);
  lines.push(`${T}var frames := SpriteFrames.new()`);
  lines.push(`${T}frames.remove_animation(&"default")`);
  lines.push(``);

  for (const anim of json.animations) {
    lines.push(`${T}# ${anim.name}`);
    lines.push(`${T}frames.add_animation(&"${anim.name}")`);
    lines.push(`${T}frames.set_animation_speed(&"${anim.name}", ${anim.fps})`);
    lines.push(`${T}frames.set_animation_loop(&"${anim.name}", true)`);
    lines.push(`${T}for region: Rect2 in [`);
    for (const quad of anim.quads) {
      lines.push(`${T}${T}Rect2(${quad.x}, ${quad.y}, ${quad.w}, ${quad.h}),`);
    }
    lines.push(`${T}]:`);
    lines.push(`${T}${T}var atlas := AtlasTexture.new()`);
    lines.push(`${T}${T}atlas.atlas = texture`);
    lines.push(`${T}${T}atlas.region = region`);
    lines.push(`${T}${T}frames.add_frame(&"${anim.name}", atlas)`);
    lines.push(``);
  }

  lines.push(`${T}return frames`);

  return lines.join("\n");
};

export const createGodotExample = (
  json: SpritesheetJSON,
  className = "SpriteSheetHelper",
): string => {
  const firstName = json.animations[0]?.name ?? "walk";
  return [
    `extends Node2D`,
    ``,
    `var animated_sprite: AnimatedSprite2D`,
    ``,
    `func _ready() -> void:`,
    `\tanimated_sprite = AnimatedSprite2D.new()`,
    `\tanimated_sprite.sprite_frames = ${className}.create_sprite_frames()`,
    `\tanimated_sprite.position = Vector2(160, 120)`,
    `\tadd_child(animated_sprite)`,
    `\tanimated_sprite.play("${firstName}")`,
    ``,
    `func _process(_delta: float) -> void:`,
    `\t# your game logic here`,
    `\tpass`,
  ].join("\n");
};

export const godotExporter: Exporter<"godot"> = {
  id: "godot",
  label: "Godot (GDScript)",

  async run({
    exportedImages,
    includeNormalMap,
    atlasOptions,
    spritePostprocess,
  }) {
    const sheets = await buildSheetAssets(exportedImages, {
      includeNormalMap,
      atlasOptions,
      exporterId: "godot",
      spritePostprocess,
    });
    for (const sheet of sheets) {
      assertSinglePageAtlas(sheet.assets, "Godot");
    }
    const helperName = (sheet: (typeof sheets)[number]) =>
      sheet.multi
        ? `${toSheetIdentifier(sheet.base)}Helper`
        : "SpriteSheetHelper";

    return {
      filename: "godot.zip",
      files: [
        ...sheets.flatMap((sheet) => [
          ...sheetImageFiles(sheet),
          sheet.assets.manifestFile,
          {
            name: `${helperName(sheet)}.gd`,
            content: createGodotGD(
              sheet.assets.json,
              sheet.imagePath,
              helperName(sheet),
            ),
          },
        ]),
        {
          name: "ExamplePlayer.gd",
          content: createGodotExample(
            sheets[0].assets.json,
            helperName(sheets[0]),
          ),
        },
      ],
    };
  },
};
