import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import {
  assertSinglePageAtlas,
  buildSheetAssets,
  sheetImageFiles,
} from "./helpers";

export const createPhaserAtlasJSON = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const frames: Record<string, object> = {};

  for (const anim of json.animations) {
    anim.quads.forEach((quad, i) => {
      frames[`${anim.name}_${i}`] = {
        frame: { x: quad.x, y: quad.y, w: quad.w, h: quad.h },
        rotated: false,
        trimmed: false,
        spriteSourceSize: { x: 0, y: 0, w: quad.w, h: quad.h },
        sourceSize: { w: quad.w, h: quad.h },
      };
    });
  }

  return JSON.stringify(
    {
      frames,
      meta: {
        image: imagePath,
        scale: "1",
      },
    },
    null,
    2,
  );
};

export const createPhaserTS = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
  atlasPath = "spritesheet_atlas.json",
): string => {
  const key = imagePath.replace(/\.[^/.]+$/, "");
  const lines: string[] = [];

  lines.push(`// Generated by Sprite Sheet Helper`);
  lines.push(`// ${json.meta.exportedAt}`);
  lines.push(`//`);
  lines.push(
    `// 1. Add "spritesheet.png" and "spritesheet_atlas.json" to your assets folder.`,
  );
  lines.push(`// 2. Call preload() inside your Scene preload().`);
  lines.push(`// 3. Call createAnims() inside your Scene create().`);
  lines.push(``);
  lines.push(`const SHEET_KEY = "${key}";`);
  lines.push(``);
  lines.push(`export function preload(scene: Phaser.Scene): void {`);
  lines.push(`  scene.load.atlas(SHEET_KEY, "${imagePath}", "${atlasPath}");`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function createAnims(scene: Phaser.Scene): void {`);

  for (const anim of json.animations) {
    lines.push(``);
    lines.push(`  // ${anim.name}`);
    lines.push(`  scene.anims.create({`);
    lines.push(`    key: "${anim.name}",`);
    lines.push(`    frames: [`);
    anim.quads.forEach((_, i) => {
      lines.push(`      { key: SHEET_KEY, frame: "${anim.name}_${i}" },`);
    });
    lines.push(`    ],`);
    lines.push(`    frameRate: ${anim.fps},`);
    lines.push(`    repeat: -1,`);
    lines.push(`  });`);
  }

  lines.push(`}`);
  lines.push(``);
  lines.push(`// Usage:`);
  lines.push(`//   const sprite = scene.add.sprite(x, y, SHEET_KEY);`);
  lines.push(`//   sprite.play("${json.animations[0]?.name ?? "animName"}");`);

  return lines.join("\n");
};

/**
 * A scene that loads every sheet and plays the first animation of the first.
 *
 * Each sheet is its own module with its own texture key, so a grouped export
 * needs all of them preloaded before any of them can be drawn — the example
 * shows that wiring rather than only the sheet it happens to play.
 */
export const createPhaserExample = (
  sheets: { base: string; json: SpritesheetJSON }[],
): string => {
  const first = sheets[0];
  const firstName = first?.json.animations[0]?.name ?? "walk";
  const moduleName = (base: string) => `${base}_phaser`;
  const alias = (base: string) =>
    base
      .split(/[-_\s]+/)
      .filter(Boolean)
      .map((word, index) =>
        index === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1),
      )
      .join("");

  return [
    `import { Scene, GameObjects } from "phaser";`,
    ``,
    ...sheets.map(
      (sheet) =>
        `import * as ${alias(sheet.base)} from "./${moduleName(sheet.base)}";`,
    ),
    ``,
    `export class Game extends Scene {`,
    `  private player!: GameObjects.Sprite;`,
    `  constructor() {`,
    `    super("Game");`,
    `  }`,
    ``,
    `  preload() {`,
    `    this.load.setPath("assets");`,
    ...sheets.map((sheet) => `    ${alias(sheet.base)}.preload(this);`),
    `  }`,
    ``,
    `  create() {`,
    ...sheets.map((sheet) => `    ${alias(sheet.base)}.createAnims(this);`),
    `    this.player = this.add.sprite(160, 120, "${first?.base ?? "spritesheet"}");`,
    `    this.player.play("${firstName}");`,
    `  }`,
    `}`,
  ].join("\n");
};

export const phaserExporter: Exporter<"phaser"> = {
  id: "phaser",
  label: "PhaserJS",

  async run({
    exportedImages,
    includeNormalMap,
    atlasOptions,
    spritePostprocess,
  }) {
    const sheets = await buildSheetAssets(exportedImages, {
      includeNormalMap,
      atlasOptions,
      exporterId: "phaser",
      spritePostprocess,
    });
    for (const sheet of sheets) {
      assertSinglePageAtlas(sheet.assets, "PhaserJS");
    }

    return {
      filename: "phaser.zip",
      files: [
        ...sheets.flatMap((sheet) => {
          const atlasPath = `${sheet.base}_atlas.json`;
          return [
            ...sheetImageFiles(sheet),
            {
              name: atlasPath,
              content: createPhaserAtlasJSON(
                sheet.assets.json,
                sheet.imagePath,
              ),
            },
            sheet.assets.manifestFile,
            {
              name: `${sheet.base}_phaser.ts`,
              content: createPhaserTS(
                sheet.assets.json,
                sheet.imagePath,
                atlasPath,
              ),
            },
          ];
        }),
        {
          name: "example.ts",
          content: createPhaserExample(
            sheets.map((sheet) => ({
              base: sheet.base,
              json: sheet.assets.json,
            })),
          ),
        },
      ],
    };
  },
};
