import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import {
  assertSinglePageAtlas,
  buildSheetAssets,
  sheetImageFiles,
} from "./helpers";

export const createPygamePy = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const lines: string[] = [];

  lines.push(`# Generated by Sprite Sheet Helper`);
  lines.push(`# ${json.meta.exportedAt}`);
  lines.push(``);
  lines.push(`import pygame`);
  lines.push(`from dataclasses import dataclass, field`);
  lines.push(`from typing import List`);
  lines.push(``);
  lines.push(`SPRITESHEET_PATH = "${imagePath}"`);
  lines.push(``);
  lines.push(``);
  lines.push(`@dataclass`);
  lines.push(`class Animation:`);
  lines.push(`    frames: List[pygame.Surface]`);
  lines.push(`    fps: float`);
  lines.push(`    frame_width: int`);
  lines.push(`    frame_height: int`);
  lines.push(`    current_frame: int = 0`);
  lines.push(`    timer: float = 0.0`);
  lines.push(``);
  lines.push(`    def update(self, dt: float) -> None:`);
  lines.push(`        self.timer += dt`);
  lines.push(`        if self.timer >= 1.0 / self.fps:`);
  lines.push(`            self.timer -= 1.0 / self.fps`);
  lines.push(
    `            self.current_frame = (self.current_frame + 1) % len(self.frames)`,
  );
  lines.push(``);
  lines.push(
    `    def draw(self, surface: pygame.Surface, x: int, y: int) -> None:`,
  );
  lines.push(`        surface.blit(self.frames[self.current_frame], (x, y))`);
  lines.push(``);
  lines.push(``);
  lines.push(`def load(path: str = SPRITESHEET_PATH) -> dict[str, Animation]:`);
  lines.push(
    `    """Load the spritesheet and return all animations keyed by name."""`,
  );
  lines.push(`    sheet = pygame.image.load(path).convert_alpha()`);
  lines.push(`    animations: dict[str, Animation] = {}`);
  lines.push(``);

  for (const anim of json.animations) {
    lines.push(`    # ${anim.name}`);
    lines.push(`    animations["${anim.name}"] = Animation(`);
    lines.push(`        frames=[`);
    for (const quad of anim.quads) {
      lines.push(
        `            sheet.subsurface(pygame.Rect(${quad.x}, ${quad.y}, ${quad.w}, ${quad.h})),`,
      );
    }
    lines.push(`        ],`);
    lines.push(`        fps=${anim.fps},`);
    lines.push(`        frame_width=${anim.frameWidth},`);
    lines.push(`        frame_height=${anim.frameHeight},`);
    lines.push(`    )`);
    lines.push(``);
  }

  lines.push(`    return animations`);
  lines.push(``);
  lines.push(``);
  lines.push(`# Usage:`);
  lines.push(`# pygame.init()`);
  lines.push(`# anims = load()`);
  lines.push(`# dt = clock.tick(60) / 1000.0`);
  lines.push(`# anims["${json.animations[0]?.name ?? "walk"}"].update(dt)`);
  lines.push(
    `# anims["${json.animations[0]?.name ?? "walk"}"].draw(screen, x, y)`,
  );

  return lines.join("\n");
};

export const createPygameExample = (
  json: SpritesheetJSON,
  moduleName = "spritesheet",
): string => {
  const firstName = json.animations[0]?.name ?? "walk";
  return [
    `import pygame`,
    `from ${moduleName} import load`,
    ``,
    `pygame.init()`,
    `screen = pygame.display.set_mode((320, 240))`,
    `clock  = pygame.time.Clock()`,
    ``,
    `anims  = load()`,
    `player = anims["${firstName}"]`,
    ``,
    `running = True`,
    `while running:`,
    `    dt = clock.tick(60) / 1000.0`,
    `    for event in pygame.event.get():`,
    `        if event.type == pygame.QUIT:`,
    `            running = False`,
    ``,
    `    player.update(dt)`,
    ``,
    `    screen.fill((0, 0, 0))`,
    `    player.draw(screen, 144, 104)`,
    `    pygame.display.flip()`,
    ``,
    `pygame.quit()`,
  ].join("\n");
};

export const pygameExporter: Exporter<"pygame"> = {
  id: "pygame",
  label: "Pygame",

  async run({
    exportedImages,
    includeNormalMap,
    atlasOptions,
    spritePostprocess,
  }) {
    const sheets = await buildSheetAssets(exportedImages, {
      includeNormalMap,
      atlasOptions,
      exporterId: "pygame",
      spritePostprocess,
    });
    for (const sheet of sheets) {
      assertSinglePageAtlas(sheet.assets, "Pygame");
    }

    return {
      filename: "pygame.zip",
      files: [
        ...sheets.flatMap((sheet) => [
          ...sheetImageFiles(sheet),
          sheet.assets.manifestFile,
          {
            name: `${sheet.base}.py`,
            content: createPygamePy(sheet.assets.json, sheet.imagePath),
          },
        ]),
        {
          name: "main.py",
          content: createPygameExample(sheets[0].assets.json, sheets[0].base),
        },
      ],
    };
  },
};
