import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import {
  assertSinglePageAtlas,
  buildSheetAssets,
  sheetImageFiles,
} from "./helpers";
import { toSheetIdentifier } from "./sheets";

/**
 * C has one namespace, so a grouped export prefixes every symbol with the
 * sheet: two headers that both define `Animation` and `UpdateAnimation` cannot
 * be included in the same translation unit. An empty prefix — a single sheet —
 * emits exactly the header this exporter has always written.
 */
export const createRaylibH = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
  prefix = "",
): string => {
  const toFloat = (n: number) => (Number.isInteger(n) ? `${n}.0f` : `${n}f`);

  const toIdentifier = (name: string) =>
    name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^([0-9])/, "_$1");

  const toPascal = (name: string) =>
    toIdentifier(name)
      .split("_")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join("");

  const screamingPrefix = prefix
    ? `${toIdentifier(prefix).toUpperCase()}_`
    : "";
  const lowerPrefix = prefix ? `${toIdentifier(prefix).toLowerCase()}_` : "";
  const guardName = `${screamingPrefix}SPRITESHEET_H`;
  const pathMacro = `${screamingPrefix}SPRITESHEET_PATH`;
  const animType = `${prefix}Animation`;
  const lines: string[] = [];

  lines.push(`// Generated by Sprite Sheet Helper`);
  lines.push(`// ${json.meta.exportedAt}`);
  lines.push(`//`);
  lines.push(`// Requires raylib — https://www.raylib.com`);
  lines.push(`// Place "${imagePath}" next to your executable, then:`);
  lines.push(`//`);
  lines.push(`//   Texture2D sheet = LoadTexture(${pathMacro});`);
  lines.push(
    `//   ${animType} walk   = Create${prefix}${toPascal(json.animations[0]?.name ?? "Walk")}Animation();`,
  );
  lines.push(`//   Update${prefix}Animation(&walk, GetFrameTime());`);
  lines.push(`//   Draw${prefix}Animation(&walk, sheet, x, y, WHITE);`);
  lines.push(``);
  lines.push(`#ifndef ${guardName}`);
  lines.push(`#define ${guardName}`);
  lines.push(``);
  lines.push(`#include "raylib.h"`);
  lines.push(``);
  lines.push(`#define ${pathMacro} "${imagePath}"`);
  lines.push(``);
  lines.push(`typedef struct {`);
  lines.push(`    Rectangle *frames;`);
  lines.push(`    int        frame_count;`);
  lines.push(`    float      fps;`);
  lines.push(`    int        frame_width;`);
  lines.push(`    int        frame_height;`);
  lines.push(`    int        current_frame;`);
  lines.push(`    float      timer;`);
  lines.push(`} ${animType};`);
  lines.push(``);
  lines.push(
    `static inline void Update${prefix}Animation(${animType} *anim, float dt) {`,
  );
  lines.push(`    anim->timer += dt;`);
  lines.push(`    if (anim->timer >= 1.0f / anim->fps) {`);
  lines.push(`        anim->timer -= 1.0f / anim->fps;`);
  lines.push(
    `        anim->current_frame = (anim->current_frame + 1) % anim->frame_count;`,
  );
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`static inline void Draw${prefix}Animation(`);
  lines.push(
    `    ${animType} *anim, Texture2D sheet, int x, int y, Color tint`,
  );
  lines.push(`) {`);
  lines.push(`    DrawTextureRec(`);
  lines.push(`        sheet,`);
  lines.push(`        anim->frames[anim->current_frame],`);
  lines.push(`        (Vector2){ (float)x, (float)y },`);
  lines.push(`        tint`);
  lines.push(`    );`);
  lines.push(`}`);
  lines.push(``);

  for (const anim of json.animations) {
    const varName = `${lowerPrefix}${toIdentifier(anim.name).toLowerCase()}`;
    const pascal = toPascal(anim.name);

    lines.push(`// ${anim.name}`);
    lines.push(`static Rectangle ${varName}_frames[] = {`);
    for (const quad of anim.quads) {
      lines.push(
        `    { ${toFloat(quad.x)}, ${toFloat(quad.y)}, ${toFloat(quad.w)}, ${toFloat(quad.h)} },`,
      );
    }
    lines.push(`};`);
    lines.push(``);
    lines.push(
      `static inline ${animType} Create${prefix}${pascal}Animation(void) {`,
    );
    lines.push(`    ${animType} anim = {`);
    lines.push(`        .frames        = ${varName}_frames,`);
    lines.push(`        .frame_count   = ${anim.quads.length},`);
    lines.push(`        .fps           = ${toFloat(anim.fps)},`);
    lines.push(`        .frame_width   = ${anim.frameWidth},`);
    lines.push(`        .frame_height  = ${anim.frameHeight},`);
    lines.push(`        .current_frame = 0,`);
    lines.push(`        .timer         = 0.0f,`);
    lines.push(`    };`);
    lines.push(`    return anim;`);
    lines.push(`}`);
    lines.push(``);
  }

  lines.push(`#endif // ${guardName}`);

  return lines.join("\n");
};

/**
 * A `main.c` that includes every sheet's header and animates the first.
 *
 * Including them all is the point: it is the file that proves the generated
 * headers can coexist, which is the whole reason their symbols are prefixed.
 */
export const createRaylibExample = (
  sheets: { base: string; prefix: string; json: SpritesheetJSON }[],
): string => {
  const first = sheets[0];
  const firstName = first?.json.animations[0]?.name ?? "walk";
  const prefix = first?.prefix ?? "";
  const pascal = firstName
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const screaming = prefix ? `${prefix.toUpperCase()}_` : "";

  return [
    `#include "raylib.h"`,
    ...sheets.map((sheet) => `#include "${sheet.base}.h"`),
    ``,
    `int main(void) {`,
    `    InitWindow(320, 240, "Sprite Animation");`,
    `    SetTargetFPS(60);`,
    ``,
    `    Texture2D sheet = LoadTexture(${screaming}SPRITESHEET_PATH);`,
    `    ${prefix}Animation  anim  = Create${prefix}${pascal}Animation();`,
    ``,
    `    while (!WindowShouldClose()) {`,
    `        Update${prefix}Animation(&anim, GetFrameTime());`,
    ``,
    `        BeginDrawing();`,
    `            ClearBackground(BLACK);`,
    `            Draw${prefix}Animation(&anim, sheet, 144, 104, WHITE);`,
    `        EndDrawing();`,
    `    }`,
    ``,
    `    UnloadTexture(sheet);`,
    `    CloseWindow();`,
    `    return 0;`,
    `}`,
  ].join("\n");
};

export const raylibExporter: Exporter<"raylib"> = {
  id: "raylib",
  label: "Raylib",

  async run({
    exportedImages,
    includeNormalMap,
    atlasOptions,
    spritePostprocess,
  }) {
    const sheets = await buildSheetAssets(exportedImages, {
      includeNormalMap,
      atlasOptions,
      exporterId: "raylib",
      spritePostprocess,
    });
    for (const sheet of sheets) {
      assertSinglePageAtlas(sheet.assets, "raylib");
    }
    const prefixed = sheets.map((sheet) => ({
      ...sheet,
      prefix: sheet.multi ? toSheetIdentifier(sheet.base) : "",
    }));

    return {
      filename: "raylib.zip",
      files: [
        ...prefixed.flatMap((sheet) => [
          ...sheetImageFiles(sheet),
          sheet.assets.manifestFile,
          {
            name: `${sheet.base}.h`,
            content: createRaylibH(
              sheet.assets.json,
              sheet.imagePath,
              sheet.prefix,
            ),
          },
        ]),
        {
          name: "main.c",
          content: createRaylibExample(
            prefixed.map((sheet) => ({
              base: sheet.base,
              prefix: sheet.prefix,
              json: sheet.assets.json,
            })),
          ),
        },
      ],
    };
  },
};
