import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import {
  assertSinglePageAtlas,
  buildSheetAssets,
  sheetImageFiles,
} from "./helpers";
import { toSheetIdentifier } from "./sheets";

/**
 * A C# class name is unique per assembly, so each sheet gets its own component:
 * two sheets both called `SpriteSheetAnimator` would not compile together. A
 * single sheet keeps the original name.
 */
export const createUnityCS = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
  className = "SpriteSheetAnimator",
): string => {
  // Resources.Load omits the extension
  const resourceName = imagePath.replace(/\.[^/.]+$/, "");
  const lines: string[] = [];

  lines.push(`// Generated by Sprite Sheet Helper`);
  lines.push(`// ${json.meta.exportedAt}`);
  lines.push(`//`);
  lines.push(`// 1. Place "${imagePath}" inside Assets/Resources/.`);
  lines.push(
    `// 2. Attach ${className} to a GameObject that has a SpriteRenderer.`,
  );
  lines.push(
    `// 3. Call animator.Play("${json.animations[0]?.name ?? "walk"}") to start an animation.`,
  );
  lines.push(``);
  lines.push(`using System.Collections.Generic;`);
  lines.push(`using UnityEngine;`);
  lines.push(``);
  lines.push(`public class ${className} : MonoBehaviour`);
  lines.push(`{`);
  lines.push(`    private struct FrameRect`);
  lines.push(`    {`);
  lines.push(`        public int X, Y, W, H;`);
  lines.push(`    }`);
  lines.push(``);
  lines.push(`    private class AnimData`);
  lines.push(`    {`);
  lines.push(`        public string   Name;`);
  lines.push(`        public FrameRect[] Frames;`);
  lines.push(`        public float    Fps;`);
  lines.push(`        public int      FrameWidth;`);
  lines.push(`        public int      FrameHeight;`);
  lines.push(`    }`);
  lines.push(``);

  // Static animation definitions
  lines.push(`    private static readonly AnimData[] Definitions =`);
  lines.push(`    {`);
  for (const anim of json.animations) {
    lines.push(`        new AnimData {`);
    lines.push(`            Name        = "${anim.name}",`);
    lines.push(`            Fps         = ${anim.fps}f,`);
    lines.push(`            FrameWidth  = ${anim.frameWidth},`);
    lines.push(`            FrameHeight = ${anim.frameHeight},`);
    lines.push(`            Frames      = new FrameRect[]`);
    lines.push(`            {`);
    for (const quad of anim.quads) {
      lines.push(
        `                new FrameRect { X = ${quad.x}, Y = ${quad.y}, W = ${quad.w}, H = ${quad.h} },`,
      );
    }
    lines.push(`            },`);
    lines.push(`        },`);
  }
  lines.push(`    };`);
  lines.push(``);

  // Fields
  lines.push(`    private SpriteRenderer                    _renderer;`);
  lines.push(`    private int                               _sheetHeight;`);
  lines.push(`    private Dictionary<string, AnimData>      _anims;`);
  lines.push(`    private Dictionary<string, Sprite[]>      _sprites;`);
  lines.push(`    private AnimData                          _current;`);
  lines.push(`    private int                               _frame;`);
  lines.push(`    private float                             _timer;`);
  lines.push(``);

  // Awake — slice sprites at runtime
  // Unity Rect origin is bottom-left, so Y must be flipped
  lines.push(`    private void Awake()`);
  lines.push(`    {`);
  lines.push(`        _renderer = GetComponent<SpriteRenderer>();`);
  lines.push(
    `        var sheet = Resources.Load<Texture2D>("${resourceName}");`,
  );
  lines.push(`        _sheetHeight = sheet.height;`);
  lines.push(``);
  lines.push(`        _anims   = new Dictionary<string, AnimData>();`);
  lines.push(`        _sprites = new Dictionary<string, Sprite[]>();`);
  lines.push(``);
  lines.push(`        foreach (var def in Definitions)`);
  lines.push(`        {`);
  lines.push(`            _anims[def.Name] = def;`);
  lines.push(`            var sprites = new Sprite[def.Frames.Length];`);
  lines.push(`            for (int i = 0; i < def.Frames.Length; i++)`);
  lines.push(`            {`);
  lines.push(`                var f = def.Frames[i];`);
  lines.push(`                // Unity Rect is bottom-left origin — flip Y`);
  lines.push(
    `                var rect = new Rect(f.X, _sheetHeight - f.Y - f.H, f.W, f.H);`,
  );
  lines.push(
    `                sprites[i] = Sprite.Create(sheet, rect, new Vector2(0.5f, 0.5f));`,
  );
  lines.push(`            }`);
  lines.push(`            _sprites[def.Name] = sprites;`);
  lines.push(`        }`);
  lines.push(`    }`);
  lines.push(``);

  // Play
  lines.push(`    public void Play(string animName)`);
  lines.push(`    {`);
  lines.push(
    `        if (_current != null && _current.Name == animName) return;`,
  );
  lines.push(
    `        if (!_anims.TryGetValue(animName, out _current)) return;`,
  );
  lines.push(`        _frame = 0;`);
  lines.push(`        _timer = 0f;`);
  lines.push(`    }`);
  lines.push(``);

  // Update
  lines.push(`    private void Update()`);
  lines.push(`    {`);
  lines.push(`        if (_current == null) return;`);
  lines.push(``);
  lines.push(`        _timer += Time.deltaTime;`);
  lines.push(`        if (_timer >= 1f / _current.Fps)`);
  lines.push(`        {`);
  lines.push(`            _timer -= 1f / _current.Fps;`);
  lines.push(
    `            _frame = (_frame + 1) % _sprites[_current.Name].Length;`,
  );
  lines.push(`        }`);
  lines.push(`        _renderer.sprite = _sprites[_current.Name][_frame];`);
  lines.push(`    }`);
  lines.push(`}`);

  return lines.join("\n");
};

export const createUnityExample = (
  json: SpritesheetJSON,
  className = "SpriteSheetAnimator",
): string => {
  const [first, second] = json.animations.map((a) => a.name);
  const hasTwo = !!second;

  return [
    `using UnityEngine;`,
    ``,
    `// Attach this alongside ${className} on the same GameObject.`,
    `public class ExamplePlayer : MonoBehaviour`,
    `{`,
    `    private ${className} _animator;`,
    ``,
    `    private void Start()`,
    `    {`,
    `        _animator = GetComponent<${className}>();`,
    `        _animator.Play("${first ?? "walk"}");`,
    `    }`,
    ``,
    `    private void Update()`,
    `    {`,
    ...(hasTwo
      ? [
          `        if (Input.GetKey(KeyCode.RightArrow))`,
          `            _animator.Play("${first}");`,
          `        else`,
          `            _animator.Play("${second}");`,
        ]
      : [`        // _animator.Play("${first ?? "walk"}");`]),
    `    }`,
    `}`,
  ].join("\n");
};

export const unityExporter: Exporter<"unity"> = {
  id: "unity",
  label: "Unity (C#)",

  async run({
    exportedImages,
    includeNormalMap,
    atlasOptions,
    spritePostprocess,
  }) {
    const sheets = await buildSheetAssets(exportedImages, {
      includeNormalMap,
      atlasOptions,
      exporterId: "unity",
      spritePostprocess,
    });
    for (const sheet of sheets) {
      assertSinglePageAtlas(sheet.assets, "Unity");
    }
    const animatorName = (sheet: (typeof sheets)[number]) =>
      sheet.multi
        ? `${toSheetIdentifier(sheet.base)}Animator`
        : "SpriteSheetAnimator";

    return {
      filename: "unity.zip",
      files: [
        ...sheets.flatMap((sheet) => [
          ...sheetImageFiles(sheet),
          sheet.assets.manifestFile,
          {
            name: `${animatorName(sheet)}.cs`,
            content: createUnityCS(
              sheet.assets.json,
              sheet.imagePath,
              animatorName(sheet),
            ),
          },
        ]),
        {
          name: "ExamplePlayer.cs",
          content: createUnityExample(
            sheets[0].assets.json,
            animatorName(sheets[0]),
          ),
        },
      ],
    };
  },
};
